### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by user2222222222** [ActionRetro/FrogFind#29]
frogfind.com has been down for over a month.  Is it coming back?

**Comment by ActionRetro** [comment]
what web browser and OS are you using?

**Comment by user2222222222** [comment]
It's working again, thank you so much!!!!

Palm Blazer v4.3 (Palm TX)
User Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; PalmSource/Palm-D050; Blazer/4.3) 16;320x448
